version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group patches only, since Cargo treats a 0.x minor bump as breaking.
    groups:
      rust-patch:
        update-types:
          - "patch"
