[package]
name = "shared"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
tracing = "0.1"
anyhow = "1.0.98"
tokio = { version = "1.34", features = ["full"] }
regex = "1"
sha2 = "0.10"

nix-utils = { path = "../nix-utils" }
