[package]
name = "nix-utils"
version = "0.1.0"
edition = "2024"
license = "LGPL-2.1-only"

[dependencies]
log = "0.4"
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
anyhow = "1.0.98"
tokio = { version = "1.34", features = ["full"] }
tokio-stream = { version = "0.1", features = ["io-util"] }
tokio-util = { version = "0.7", features = ["io", "io-util"] }
futures = "0.3"
ahash = { version = "0.8.11", features = ["serde"] }
regex = "1"
sha2 = "0.10"
url = "2.5.4"

cxx = "1"
bytes = "1.10.1"

nix-diff = { git = "https://github.com/mic92/nix-diff-rs.git", rev = "6c0902f9c6f756b09095e9d77b424332ff0e32e9" }

[build-dependencies]
cxx-build = "1"
pkg-config = "0.3"
