[package]
name                   = "hydra-evaluator"
version.workspace      = true
edition                = "2024"
license                = "GPL-3.0"
rust-version.workspace = true

[dependencies]
clap                 = { workspace = true, features = [ "derive" ] }
color-eyre.workspace = true
fs-err.workspace     = true
futures.workspace    = true
sqlx                 = { workspace = true, features = [ "runtime-tokio", "tls-rustls-ring-webpki", "postgres" ] }
thiserror.workspace  = true
tokio                = { workspace = true, features = [ "full" ] }
tracing.workspace    = true

daemon-server.workspace       = true
db                            = { path = "../crates/db" }
harmonia-store-path.workspace = true
hydra-tracing                 = { path = "../crates/tracing" }
