name: "Manual"
on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: github-pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v31
    - uses: Mic92/hestia@v3
    - run: nix-build -A packages.x86_64-linux.hydra-manual
    - uses: actions/upload-pages-artifact@v4
      with:
        path: result/share/doc/hydra
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
